import mongoose from "mongoose";
import Product from "./models/Product.js"; // Adjust the path to your schema file

// const MONGODB_URI = "mongodb://127.0.0.1:27017/afrimart";
const MONGODB_URI = process.env.MONGO_URI + process.env.DATABASE_NAME;

const products = [
  {
    name: "Ultra-Comfort Running Sneakers",
    description: "Experience unparalleled comfort with our latest breathable mesh running sneakers designed for long-distance durability.",
    price: mongoose.Types.Decimal128.fromString("890.99"),
    discount_percentage: 15,
    brand: "SwiftStep",
    category: "Shoes",
    qty: 50,
    product_image_url: "https://images.pexels.com/photos/1456733/pexels-photo-1456733.jpeg",
    rating: mongoose.Types.Decimal128.fromString("4.5"),
    features: ["Breathable Mesh", "Memory Foam Insole", "Slip-resistant"],
    specifications: { weight: "250g", material: "Synthetic" },
    color: ["Blue", "Grey", "Black"],
    warranty: { period: "1 year", type: "Manufacturer" },
    deal_tag: "Flash",
    is_new: true,
  },
  {
    name: "Ergonomic Office Task Chair",
    description: "Upgrade your workspace with this high-back ergonomic chair featuring adjustable lumbar support and mesh backing.",
    price: mongoose.Types.Decimal128.fromString("19900.50"),
    discount_percentage: 0,
    brand: "WorkFlow",
    category: "Furniture",
    qty: 20,
    product_image_url: "https://images.pexels.com/photos/5483154/pexels-photo-5483154.jpeg",
    rating: mongoose.Types.Decimal128.fromString("4.8"),
    features: ["Adjustable Height", "360-degree Swivel", "Lumbar Support"],
    specifications: { max_weight: "300lbs", assembly_required: true },
    color: ["Black"],
    warranty: { period: "2 years", type: "Limited" },
    deal_tag: "Deal",
    is_new: false,
  },
  {
    name: "Stainless Steel Smart Kettle",
    description: "A fast-boiling 1.7L electric kettle with precise temperature control and a sleek brushed metal finish.",
    price: mongoose.Types.Decimal128.fromString("5400.00"),
    discount_percentage: 10,
    brand: "KitchenPro",
    category: "Home",
    qty: 100,
    product_image_url: "https://images.pexels.com/photos/17837368/pexels-photo-17837368.jpeg",
    rating: mongoose.Types.Decimal128.fromString("4.2"),
    features: ["Auto-shutoff", "Keep Warm Function", "LED Display"],
    specifications: { capacity: "1.7L", wattage: "1500W" },
    color: ["Silver"],
    warranty: { period: "6 months", type: "Replacement" },
    deal_tag: null,
    is_new: true,
  },
  {
    name: "Classic Leather Loafer Shoes",
    description: "Timeless leather loafers with cushioned insoles and a refined silhouette, ideal for office wear and formal outings.",
    price: mongoose.Types.Decimal128.fromString("740.95"),
    discount_percentage: 5,
    brand: "HeritageWalk",
    category: "Shoes",
    qty: 35,
    product_image_url: "https://images.pexels.com/photos/19556446/pexels-photo-19556446.jpeg",
    rating: mongoose.Types.Decimal128.fromString("4.1"),
    features: ["Genuine Leather", "Cushioned Insole", "Non-marking Sole"],
    specifications: { upper: "Leather", lining: "Textile", sole: "Rubber" },
    color: ["Brown", "Black"],
    warranty: { period: "6 months", type: "Manufacturer" },
    deal_tag: "Deal",
    is_new: false,
  },
  {
    name: "Trail-Grip Hiking Boots Pro",
    description: "Rugged waterproof hiking boots built for traction on wet terrain, with ankle support for long treks and daily use.",
    price: mongoose.Types.Decimal128.fromString("1290.00"),
    discount_percentage: 20,
    brand: "SummitRidge",
    category: "Shoes",
    qty: 22,
    product_image_url: "https://images.pexels.com/photos/32323415/pexels-photo-32323415.jpeg",
    rating: mongoose.Types.Decimal128.fromString("4.6"),
    features: ["Waterproof Membrane", "Vibram-style Grip", "Ankle Support"],
    specifications: { waterproof: true, weight: "410g", toe: "Reinforced" },
    color: ["Olive", "Brown"],
    warranty: { period: "1 year", type: "Limited" },
    deal_tag: "Flash",
    is_new: true,
  },
  {
    name: "Everyday Cotton T-Shirt Pack",
    description: "Soft breathable cotton tees in a convenient multi-pack, designed for all-day comfort and easy everyday layering.",
    price: mongoose.Types.Decimal128.fromString("600.99"),
    discount_percentage: 0,
    brand: "BasicsCo",
    category: "Clothes",
    qty: 120,
    product_image_url: "https://images.pexels.com/photos/8532616/pexels-photo-8532616.jpeg",
    rating: mongoose.Types.Decimal128.fromString("4.0"),
    features: ["100% Cotton", "Tagless Neck", "Pre-shrunk Fabric"],
    specifications: { fit: "Regular", care: "Machine wash", pack_size: 3 },
    color: ["White", "Black", "Navy"],
    warranty: { period: "30 days", type: "Return" },
    deal_tag: null,
    is_new: false,
  },
  {
    name: "Warm Fleece Hoodie Essential",
    description: "Cozy fleece hoodie with a brushed interior and durable stitching, perfect for cool evenings and casual streetwear.",
    price: mongoose.Types.Decimal128.fromString("3900.50"),
    discount_percentage: 12,
    brand: "UrbanKnit",
    category: "Clothes",
    qty: 60,
    product_image_url: "https://images.pexels.com/photos/6311642/pexels-photo-6311642.jpeg",
    rating: mongoose.Types.Decimal128.fromString("4.4"),
    features: ["Brushed Fleece", "Kangaroo Pocket", "Drawstring Hood"],
    specifications: { material: "Cotton blend", fit: "Relaxed" },
    color: ["Charcoal", "Cream", "Forest Green"],
    warranty: { period: "60 days", type: "Return" },
    deal_tag: "Deal",
    is_new: true,
  },
  {
    name: "Organic Jasmine Rice 5kg Bag",
    description: "Fragrant long-grain jasmine rice sourced from organic farms, ideal for fluffy meals, stir-fries, and family servings.",
    price: mongoose.Types.Decimal128.fromString("1800.75"),
    discount_percentage: 8,
    brand: "FarmHarvest",
    category: "Food",
    qty: 200,
    product_image_url: "https://cdn11.bigcommerce.com/s-dis4vxtxtc/images/stencil/608x608/products/2094/4622/Organic-Jasmine-Rice-5KG-Front_RIJAS2__54679.1679026637.jpg?c=2",
    rating: mongoose.Types.Decimal128.fromString("4.7"),
    features: ["Organic", "Aromatic Grains", "Low Broken Percentage"],
    specifications: { weight: "5kg", origin: "Thailand" },
    color: [],
    warranty: { period: "14 days", type: "Quality" },
    deal_tag: "Bundle",
    is_new: false,
  },
  {
    name: "Roasted Arabica Coffee Beans 1kg",
    description: "Medium roast 100% arabica coffee beans with chocolate notes and balanced acidity, freshly packed for rich espresso.",
    price: mongoose.Types.Decimal128.fromString("2100.90"),
    discount_percentage: 0,
    brand: "RoastCraft",
    category: "Food",
    qty: 85,
    product_image_url: "https://i.ebayimg.com/images/g/ztEAAOSw--1WqgOq/s-l400.jpg",
    rating: mongoose.Types.Decimal128.fromString("4.3"),
    features: ["100% Arabica", "Medium Roast", "Resealable Bag"],
    specifications: { weight: "1kg", roast: "Medium", grind: "Whole bean" },
    color: [],
    warranty: { period: "30 days", type: "Replacement" },
    deal_tag: null,
    is_new: true,
  },
  {
    name: "Noise-Cancel Bluetooth Headphones X2",
    description: "Wireless over-ear headphones with active noise cancellation, long battery life, and clear microphones for calls.",
    price: mongoose.Types.Decimal128.fromString("14900.99"),
    discount_percentage: 18,
    brand: "SoundPulse",
    category: "Electronics",
    qty: 40,
    product_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6_38X4hQ9hV7g3zKjQrN0Wg704KgWg27Xog&s",
    rating: mongoose.Types.Decimal128.fromString("4.5"),
    features: ["Active Noise Canceling", "40h Battery", "Fast Charge"],
    specifications: { bluetooth: "5.3", charging: "USB-C", latency: "Low" },
    color: ["Black", "Sand"],
    warranty: { period: "1 year", type: "Manufacturer" },
    deal_tag: "Clearance",
    is_new: false,
  },
  {
    name: "Compact 4K Action Camera Kit",
    description: "Capture crisp 4K video with stabilization and waterproof housing, plus mounts for bikes, helmets, and adventures.",
    price: mongoose.Types.Decimal128.fromString("11900.00"),
    discount_percentage: 10,
    brand: "ActionForge",
    category: "Electronics",
    qty: 28,
    product_image_url: "https://cdn.mos.cms.futurecdn.net/nWk7gGiXtyA79QRfd2Fmak.jpg",
    rating: mongoose.Types.Decimal128.fromString("4.1"),
    features: ["4K Recording", "Image Stabilization", "Waterproof Case"],
    specifications: { resolution: "4K", waterproof_depth: "30m", storage: "microSD" },
    color: ["Black"],
    warranty: { period: "1 year", type: "Limited" },
    deal_tag: "Deal",
    is_new: true,
  },
  {
    name: "Minimalist Leather Wallet Slim",
    description: "Slim leather wallet with RFID blocking and smart card slots, designed to reduce bulk while keeping essentials secure.",
    price: mongoose.Types.Decimal128.fromString("19.99"),
    discount_percentage: 0,
    brand: "CarryLite",
    category: "Accessories",
    qty: 150,
    product_image_url: "https://images.squarespace-cdn.com/content/v1/5a8300bdf09ca43baa039bee/e2de473c-68f4-4115-87ce-d4a0d56bfb1b/IMG_3056.jpg?format=1000w",
    rating: mongoose.Types.Decimal128.fromString("4.2"),
    features: ["RFID Blocking", "Slim Profile", "Scratch Resistant"],
    specifications: { slots: 6, material: "Leather", money_clip: true },
    color: ["Tan", "Black"],
    warranty: { period: "90 days", type: "Replacement" },
    deal_tag: null,
    is_new: false,
  },
  {
    name: "Polarized Sunglasses UV400 Sport",
    description: "Durable polarized sunglasses that reduce glare and protect your eyes with UV400 lenses, ideal for driving and sports.",
    price: mongoose.Types.Decimal128.fromString("29.95"),
    discount_percentage: 15,
    brand: "SunGuard",
    category: "Accessories",
    qty: 95,
    product_image_url: "https://m.media-amazon.com/images/I/61N2dye1cQL._AC_UF1000,1000_QL80_.jpg",
    rating: mongoose.Types.Decimal128.fromString("4.4"),
    features: ["Polarized Lenses", "UV400 Protection", "Lightweight Frame"],
    specifications: { lens: "TAC", frame: "TR90", fit: "Medium" },
    color: ["Matte Black", "Tortoise"],
    warranty: { period: "6 months", type: "Limited" },
    deal_tag: "Flash",
    is_new: true,
  },
  {
    name: "Solid Wood Coffee Table Modern",
    description: "Modern solid wood coffee table with a smooth finish and sturdy legs, sized for living rooms and compact spaces.",
    price: mongoose.Types.Decimal128.fromString("179.00"),
    discount_percentage: 0,
    brand: "OakLine",
    category: "Furniture",
    qty: 12,
    product_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA65ZIWdSbxzu_icuPmIyQqZf58nlihst10w&s",
    rating: mongoose.Types.Decimal128.fromString("4.6"),
    features: ["Solid Wood", "Easy Assembly", "Scratch Resistant Finish"],
    specifications: { dimensions: "100x50x45cm", material: "Oak" },
    color: ["Natural Oak", "Walnut"],
    warranty: { period: "2 years", type: "Limited" },
    deal_tag: null,
    is_new: false,
  },
  {
    name: "Memory Foam Mattress Topper Queen",
    description: "Pressure-relieving memory foam topper that improves comfort and support, with breathable cover for cooler sleep.",
    price: mongoose.Types.Decimal128.fromString("8900.00"),
    discount_percentage: 22,
    brand: "SleepNest",
    category: "Home",
    qty: 45,
    product_image_url: "https://images-na.ssl-images-amazon.com/images/I/81H3-5WU+GL.jpg",
    rating: mongoose.Types.Decimal128.fromString("4.3"),
    features: ["Pressure Relief", "Breathable Cover", "Non-slip Bottom"],
    specifications: { size: "Queen", thickness: "5cm", cover: "Removable" },
    color: ["White"],
    warranty: { period: "1 year", type: "Limited" },
    deal_tag: "Clearance",
    is_new: true,
  },
  {
    name: "Nonstick Cookware Set 10-Piece",
    description: "Durable nonstick cookware set with even heating and ergonomic handles, designed for daily cooking and easy cleanup.",
    price: mongoose.Types.Decimal128.fromString("10900.50"),
    discount_percentage: 10,
    brand: "ChefEase",
    category: "Home",
    qty: 30,
    product_image_url: "https://images-cdn.ubuy.qa/64c36fa2222ca651572091e8-tramontina-primaware-non-stick-cookware.jpg",
    rating: mongoose.Types.Decimal128.fromString("4.2"),
    features: ["PFOA-Free", "Even Heat Distribution", "Oven Safe Lids"],
    specifications: { pieces: 10, compatibility: "Gas/Electric", care: "Hand wash" },
    color: ["Black"],
    warranty: { period: "1 year", type: "Manufacturer" },
    deal_tag: "Bundle",
    is_new: false,
  },
  {
    name: "Adjustable Dumbbell Set 2x24kg",
    description: "Space-saving adjustable dumbbells that replace multiple weights, perfect for home workouts, strength training, and HIIT.",
    price: mongoose.Types.Decimal128.fromString("24900.00"),
    discount_percentage: 0,
    brand: "IronFlex",
    category: "Sports & Outdoors",
    qty: 14,
    product_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROkkH1uMGnDxoGJHC_ge87L825EdsxCnlODA&s",
    rating: mongoose.Types.Decimal128.fromString("4.7"),
    features: ["Quick Adjust Dial", "Compact Storage", "Anti-slip Handle"],
    specifications: { set: "Pair", max_weight_each: "24kg", increments: "2kg" },
    color: ["Black", "Red"],
    warranty: { period: "2 years", type: "Limited" },
    deal_tag: null,
    is_new: true,
  },
  {
    name: "Family Camping Tent 4-Person",
    description: "Spacious 4-person camping tent with rainfly and ventilation panels, designed for quick setup and dry nights outdoors.",
    price: mongoose.Types.Decimal128.fromString("13900.00"),
    discount_percentage: 15,
    brand: "CampHaven",
    category: "Sports & Outdoors",
    qty: 18,
    product_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-hGYKidzYB791nQ32cvl3GYZXiWmMRTcN9Q&s",
    rating: mongoose.Types.Decimal128.fromString("4.3"),
    features: ["Water Resistant", "Quick Setup", "Ventilation Mesh"],
    specifications: { capacity: 4, season: "3-season", weight: "4.8kg" },
    color: ["Green", "Grey"],
    warranty: { period: "1 year", type: "Limited" },
    deal_tag: "Deal",
    is_new: false,
  },
  {
    name: "Lightweight Everyday Slip-On Shoes",
    description: "Comfortable slip-on shoes with breathable knit upper and flexible sole, built for daily commuting and casual weekends.",
    price: mongoose.Types.Decimal128.fromString("1400.90"),
    discount_percentage: 10,
    brand: "CityStride",
    category: "Shoes",
    qty: 70,
    product_image_url: "https://m.media-amazon.com/images/I/51iXn9OiZpL._AC_UY900_.jpg",
    rating: mongoose.Types.Decimal128.fromString("4.2"),
    features: ["Breathable Knit", "Flexible Sole", "Easy Slip-On Fit"],
    specifications: { upper: "Knit", sole: "EVA", closure: "Slip-on" },
    color: ["Black", "Grey", "Navy"],
    warranty: { period: "6 months", type: "Manufacturer" },
    deal_tag: null,
    is_new: true,
  },
  {
    name: "Cushion Plus Basketball High-Tops",
    description: "Supportive high-top basketball shoes with responsive cushioning and grippy outsole, designed for quick cuts and jumps.",
    price: mongoose.Types.Decimal128.fromString("9800.00"),
    discount_percentage: 0,
    brand: "CourtMax",
    category: "Shoes",
    qty: 26,
    product_image_url: "https://m.media-amazon.com/images/I/61cQChbb3oL._AC_UF894,1000_QL80_.jpg",
    rating: mongoose.Types.Decimal128.fromString("4.3"),
    features: ["High-Top Support", "Responsive Cushion", "Durable Outsole"],
    specifications: { court: "Indoor/Outdoor", upper: "Synthetic", ankle: "Padded" },
    color: ["White", "Black", "Red"],
    warranty: { period: "1 year", type: "Limited" },
    deal_tag: "Deal",
    is_new: false,
  },
  {
    name: "Stretch Denim Jeans Regular Fit",
    description: "Classic regular-fit jeans with a touch of stretch for comfort, finished with durable seams for long-lasting wear.",
    price: mongoose.Types.Decimal128.fromString("1999.99"),
    discount_percentage: 5,
    brand: "DenimWorks",
    category: "Clothes",
    qty: 80,
    product_image_url: "https://americantall.com/cdn/shop/products/American-Tall-Men-LJ-Jeans-Straight-Leg-Machine-Blue-front.jpg?v=1762199054",
    rating: mongoose.Types.Decimal128.fromString("4.1"),
    features: ["Stretch Denim", "Reinforced Stitching", "Everyday Fit"],
    specifications: { fit: "Regular", material: "Denim blend", rise: "Mid" },
    color: ["Dark Blue", "Black"],
    warranty: { period: "60 days", type: "Return" },
    deal_tag: null,
    is_new: false,
  },
  {
    name: "Breathable Activewear Joggers Men",
    description: "Lightweight joggers with moisture-wicking fabric and zip pockets, made for training sessions or relaxed daily errands.",
    price: mongoose.Types.Decimal128.fromString("3400.75"),
    discount_percentage: 10,
    brand: "MoveDry",
    category: "Clothes",
    qty: 65,
    product_image_url: "https://vader-prod.s3.amazonaws.com/1738873310-mhl-joggers-rhone-731-67a519d8c9226.jpg",
    rating: mongoose.Types.Decimal128.fromString("4.2"),
    features: ["Moisture Wicking", "Zip Pockets", "Stretch Waistband"],
    specifications: { fit: "Tapered", material: "Poly blend", care: "Machine wash" },
    color: ["Black", "Navy", "Olive"],
    warranty: { period: "60 days", type: "Return" },
    deal_tag: "Deal",
    is_new: true,
  },
  {
    name: "Lightweight Windbreaker Jacket Unisex",
    description: "Packable windbreaker with water-resistant finish and adjustable hood, ideal for breezy days and travel packing.",
    price: mongoose.Types.Decimal128.fromString("4200.00"),
    discount_percentage: 0,
    brand: "BreezeGuard",
    category: "Clothes",
    qty: 40,
    product_image_url: "https://www.independenttradingco.com/cdn/shop/files/EXP54LWZC-ARM.jpg?v=1745961992&width=2048",
    rating: mongoose.Types.Decimal128.fromString("4.0"),
    features: ["Packable", "Water Resistant", "Adjustable Hood"],
    specifications: { material: "Nylon", lining: "Mesh", fit: "Regular" },
    color: ["Sky Blue", "Black", "Green"],
    warranty: { period: "90 days", type: "Return" },
    deal_tag: null,
    is_new: false,
  },
  {
    name: "Pure Honey Natural 500g Jar",
    description: "Golden pure honey with a smooth finish, perfect for tea, baking, and breakfast bowls, sourced from trusted beekeepers.",
    price: mongoose.Types.Decimal128.fromString("800.90"),
    discount_percentage: 0,
    brand: "BeePure",
    category: "Food",
    qty: 140,
    product_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlrvyz4-iuLFwciXteVE5MyP5ZZC-gOUWuwg&s",
    rating: mongoose.Types.Decimal128.fromString("4.6"),
    features: ["No Added Sugar", "Sealed Jar", "Naturally Sweet"],
    specifications: { weight: "500g", ingredients: "100% honey" },
    color: [],
    warranty: { period: "14 days", type: "Quality" },
    deal_tag: null,
    is_new: false,
  },
  {
    name: "Premium Spaghetti Pasta 2kg Pack",
    description: "Quality durum wheat spaghetti that cooks al dente, ideal for family meals, classic sauces, and quick weekday dinners.",
    price: mongoose.Types.Decimal128.fromString("600.50"),
    discount_percentage: 10,
    brand: "PastaCasa",
    category: "Food",
    qty: 180,
    product_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEv3Zwh9mNi2SskqJR9kjZ91q4ALmLQj_42Q&s",
    rating: mongoose.Types.Decimal128.fromString("4.4"),
    features: ["Durum Wheat", "Cooks Evenly", "Family Size Pack"],
    specifications: { weight: "2kg", wheat: "Durum", cooking_time: "9-11 min" },
    color: [],
    warranty: { period: "14 days", type: "Quality" },
    deal_tag: "Bundle",
    is_new: false,
  },
  {
    name: "Creamy Peanut Butter 1kg Jar",
    description: "Smooth peanut butter with roasted peanuts taste, great for sandwiches, smoothies, and baking with consistent texture.",
    price: mongoose.Types.Decimal128.fromString("700.99"),
    discount_percentage: 0,
    brand: "NutSmooth",
    category: "Food",
    qty: 110,
    product_image_url: "https://cdn.mafrservices.com/pim-content/KEN/media/product/1990/1758031204/1990_main.jpg",
    rating: mongoose.Types.Decimal128.fromString("4.3"),
    features: ["Creamy Texture", "Resealable Lid", "Roasted Peanut Taste"],
    specifications: { weight: "1kg", texture: "Creamy", contains: "Peanuts" },
    color: [],
    warranty: { period: "14 days", type: "Quality" },
    deal_tag: null,
    is_new: true,
  },
  {
    name: "Fast Charge USB-C Power Bank 20000mAh",
    description: "High-capacity power bank with fast charging and dual outputs, keeping phones and tablets powered throughout the day.",
    price: mongoose.Types.Decimal128.fromString("3900.99"),
    discount_percentage: 15,
    brand: "VoltMate",
    category: "Electronics",
    qty: 75,
    product_image_url: "https://fonexpress.net/wp-content/uploads/2024/02/Belkin-BoostCharge-USB-C-Power-Bank-20000mAh.webp",
    rating: mongoose.Types.Decimal128.fromString("4.4"),
    features: ["20000mAh Capacity", "Fast Charge", "Dual Output Ports"],
    specifications: { capacity: "20000mAh", input: "USB-C", outputs: 2 },
    color: ["Black", "White"],
    warranty: { period: "1 year", type: "Manufacturer" },
    deal_tag: "Flash",
    is_new: true,
  },
  {
    name: "Smart LED TV 43-Inch HDR Series",
    description: "43-inch smart TV with HDR support and streaming apps, delivering sharp visuals and smooth playback for everyday viewing.",
    price: mongoose.Types.Decimal128.fromString("28900.00"),
    discount_percentage: 8,
    brand: "ViewNova",
    category: "Electronics",
    qty: 16,
    product_image_url: "https://www.lg.com/eastafrica/images/tvs/md07561616/gallery/1600.jpg",
    rating: mongoose.Types.Decimal128.fromString("4.2"),
    features: ["HDR", "Streaming Apps", "Multiple HDMI Ports"],
    specifications: { size: "43-inch", resolution: "4K", hdr: true },
    color: ["Black"],
    warranty: { period: "2 years", type: "Limited" },
    deal_tag: "Deal",
    is_new: false,
  },
  {
    name: "Wireless Mechanical Keyboard Compact",
    description: "Compact wireless mechanical keyboard with tactile switches and long battery life, built for typing comfort and gaming use.",
    price: mongoose.Types.Decimal128.fromString("7900.00"),
    discount_percentage: 0,
    brand: "KeyForge",
    category: "Electronics",
    qty: 32,
    product_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHG4tm0MXY2qFsmpiTcibj6knALaDdrq4Yrw&s",
    rating: mongoose.Types.Decimal128.fromString("4.5"),
    features: ["Tactile Switches", "Wireless Mode", "Backlit Keys"],
    specifications: { layout: "75%", connectivity: "BT/USB", battery: "Long life" },
    color: ["Black", "White"],
    warranty: { period: "1 year", type: "Manufacturer" },
    deal_tag: null,
    is_new: true,
  },
  {
    name: "Stainless Steel Water Bottle 1L",
    description: "Insulated stainless steel bottle that keeps drinks cold or hot for hours, featuring leakproof lid for commuting and gym.",
    price: mongoose.Types.Decimal128.fromString("1600.95"),
    discount_percentage: 0,
    brand: "HydraPeak",
    category: "Accessories",
    qty: 130,
    product_image_url: "https://contents.mediadecathlon.com/p2201772/k$aacc1d78eb48b40e1eb7de8d05fa6d15/stainless-steel-isothermal-hiking-bottle-1-litre-metal.jpg",
    rating: mongoose.Types.Decimal128.fromString("4.6"),
    features: ["Insulated", "Leakproof Lid", "BPA-Free"],
    specifications: { capacity: "1L", material: "Stainless Steel", insulation: "Double wall" },
    color: ["Silver", "Matte Black", "Blue"],
    warranty: { period: "1 year", type: "Replacement" },
    deal_tag: null,
    is_new: false,
  },
  {
    name: "Travel Backpack 28L Laptop Friendly",
    description: "Durable travel backpack with padded laptop sleeve and organized compartments, designed for daily work commutes and trips.",
    price: mongoose.Types.Decimal128.fromString("2400.00"),
    discount_percentage: 12,
    brand: "PackPro",
    category: "Accessories",
    qty: 55,
    product_image_url: "https://m.media-amazon.com/images/I/713opP7c+DL._AC_UY1000_.jpg",
    rating: mongoose.Types.Decimal128.fromString("4.3"),
    features: ["Padded Laptop Sleeve", "Water Resistant", "Multiple Compartments"],
    specifications: { capacity: "28L", laptop: "15-inch", material: "Polyester" },
    color: ["Black", "Grey"],
    warranty: { period: "1 year", type: "Limited" },
    deal_tag: "Deal",
    is_new: true,
  },
  {
    name: "Classic Stainless Watch Minimal Dial",
    description: "Minimal dial wristwatch with stainless steel strap and reliable quartz movement, suitable for daily wear and formal looks.",
    price: mongoose.Types.Decimal128.fromString("5900.99"),
    discount_percentage: 0,
    brand: "TimeLine",
    category: "Accessories",
    qty: 38,
    product_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7lASJpEBiXak8WLbzPS-HpgEmMdOQHHIKUQ&s",
    rating: mongoose.Types.Decimal128.fromString("4.1"),
    features: ["Quartz Movement", "Stainless Strap", "Scratch Resistant Glass"],
    specifications: { movement: "Quartz", water_resistant: "3ATM", case: "Stainless Steel" },
    color: ["Silver", "Black"],
    warranty: { period: "1 year", type: "Manufacturer" },
    deal_tag: null,
    is_new: false,
  },
  {
    name: "Modern Bookshelf 5-Tier Storage Unit",
    description: "Five-tier storage bookshelf with sturdy frame and easy assembly, perfect for books, decor, and home office organization.",
    price: mongoose.Types.Decimal128.fromString("8900.00"),
    discount_percentage: 10,
    brand: "RoomGrid",
    category: "Furniture",
    qty: 20,
    product_image_url: "https://ak1.ostkcdn.com/images/products/is/images/direct/5b73ed4999183b6710710facb57b9cbd2e8641cf/Newport-5-Tier-Wood-Bookcase-Modern-Bookshelf-with-Open-Shelves-for-Living-Room%2C-Office-Bedroom-Sturdy-Storage-Shelf-Unit.jpg",
    rating: mongoose.Types.Decimal128.fromString("4.2"),
    features: ["5-Tier Storage", "Easy Assembly", "Sturdy Frame"],
    specifications: { tiers: 5, material: "Engineered wood", assembly_required: true },
    color: ["White", "Oak"],
    warranty: { period: "2 years", type: "Limited" },
    deal_tag: "Deal",
    is_new: true,
  },
  {
    name: "Compact Bedside Table Drawer Set",
    description: "Compact bedside table with smooth drawer and open shelf, offering convenient storage for bedroom essentials and décor.",
    price: mongoose.Types.Decimal128.fromString("5900.50"),
    discount_percentage: 0,
    brand: "NightNest",
    category: "Furniture",
    qty: 25,
    product_image_url: "https://img5.su-cdn.com/cdn-cgi/image/width=750,height=750/mall/file/2024/07/31/2500x2500_0e6e1bddf98970c7e089b22506ca4854.jpg",
    rating: mongoose.Types.Decimal128.fromString("4.0"),
    features: ["Smooth Drawer", "Open Shelf", "Compact Footprint"],
    specifications: { drawers: 1, shelf: 1, dimensions: "40x35x55cm" },
    color: ["White", "Walnut"],
    warranty: { period: "1 year", type: "Limited" },
    deal_tag: null,
    is_new: false,
  },
  {
    name: "Dining Chair Set of 2 Padded",
    description: "Comfortable padded dining chairs with sturdy legs and easy-clean upholstery, designed for dining spaces and small kitchens.",
    price: mongoose.Types.Decimal128.fromString("11900.00"),
    discount_percentage: 15,
    brand: "TableCraft",
    category: "Furniture",
    qty: 14,
    product_image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZBUAgLrx9XlYuUyCZmGE9TKNnd0h_omiXXA&s",
    rating: mongoose.Types.Decimal128.fromString("4.3"),
    features: ["Padded Seat", "Easy Clean Upholstery", "Stable Legs"],
    specifications: { set: 2, upholstery: "PU leather", max_weight: "120kg" },
    color: ["Black", "Beige"],
    warranty: { period: "2 years", type: "Limited" },
    deal_tag: "Bundle",
    is_new: false,
  },
  {
    name: "Soft Microfiber Bath Towel Set",
    description: "Absorbent microfiber towel set that dries quickly and stays soft after washes, ideal for bathroom, gym, or travel use.",
    price: mongoose.Types.Decimal128.fromString("900.50"),
    discount_percentage: 0,
    brand: "AquaSoft",
    category: "Home",
    qty: 90,
    product_image_url: "https://images.pexels.com/photos/45980/pexels-photo-45980.jpeg",
    rating: mongoose.Types.Decimal128.fromString("4.3"),
    features: ["Quick Dry", "Soft Feel", "High Absorbency"],
    specifications: { pieces: 4, material: "Microfiber", care: "Machine wash" },
    color: ["Grey", "White", "Blue"],
    warranty: { period: "30 days", type: "Return" },
    deal_tag: null,
    is_new: false,
  },
  {
    name: "Aroma Diffuser Ultrasonic 300ml",
    description: "Ultrasonic aroma diffuser with adjustable mist and soft lighting, helping freshen rooms while creating a calm atmosphere.",
    price: mongoose.Types.Decimal128.fromString("27.99"),
    discount_percentage: 10,
    brand: "CalmAir",
    category: "Home",
    qty: 55,
    product_image_url: "https://images.pexels.com/photos/6915313/pexels-photo-6915313.jpeg",
    rating: mongoose.Types.Decimal128.fromString("4.2"),
    features: ["Ultrasonic Mist", "Auto Shutoff", "Soft Night Light"],
    specifications: { capacity: "300ml", timer: "1/3/6h", noise: "Low" },
    color: ["White", "Wood Grain"],
    warranty: { period: "1 year", type: "Replacement" },
    deal_tag: "Flash",
    is_new: true,
  },
  {
    name: "Yoga Mat Non-Slip 8mm Thick",
    description: "Comfortable non-slip yoga mat with extra cushioning, suitable for yoga, pilates, stretching, and home fitness routines.",
    price: mongoose.Types.Decimal128.fromString("2200.00"),
    discount_percentage: 0,
    brand: "ZenMove",
    category: "Sports & Outdoors",
    qty: 100,
    product_image_url: "https://images.pexels.com/photos/4325462/pexels-photo-4325462.jpeg",
    rating: mongoose.Types.Decimal128.fromString("4.5"),
    features: ["Non-Slip Surface", "8mm Cushioning", "Easy Carry Strap"],
    specifications: { thickness: "8mm", length: "183cm", material: "TPE" },
    color: ["Purple", "Black", "Teal"],
    warranty: { period: "6 months", type: "Limited" },
    deal_tag: null,
    is_new: false,
  },
  {
    name: "Insulated Cooler Box 25L Portable",
    description: "Portable cooler box with strong insulation to keep drinks and snacks chilled, perfect for picnics, road trips, and camping.",
    price: mongoose.Types.Decimal128.fromString("4400.00"),
    discount_percentage: 10,
    brand: "ChillTrail",
    category: "Sports & Outdoors",
    qty: 34,
    product_image_url: "https://images.pexels.com/photos/6831179/pexels-photo-6831179.jpeg",
    rating: mongoose.Types.Decimal128.fromString("4.2"),
    features: ["Strong Insulation", "Easy Carry Handle", "Durable Shell"],
    specifications: { capacity: "25L", insulation: "High", weight: "2.6kg" },
    color: ["Blue", "Grey"],
    warranty: { period: "1 year", type: "Limited" },
    deal_tag: "Deal",
    is_new: true,
  },
  {
    name: "Football Training Ball Size 5",
    description: "Durable size 5 football with balanced weight and textured grip, designed for training sessions and casual matches.",
    price: mongoose.Types.Decimal128.fromString("1400.99"),
    discount_percentage: 0,
    brand: "FieldPro",
    category: "Sports & Outdoors",
    qty: 120,
    product_image_url: "https://images-na.ssl-images-amazon.com/images/I/71Aold8KaOL._UL500_.jpg",
    rating: mongoose.Types.Decimal128.fromString("4.1"),
    features: ["Textured Grip", "Durable Bladder", "Consistent Bounce"],
    specifications: { size: 5, surface: "All-weather", use: "Training" },
    color: ["White", "Blue"],
    warranty: { period: "90 days", type: "Replacement" },
    deal_tag: null,
    is_new: false,
  }
];

export const seedDatabase = async () => {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log("Connected to MongoDB...");

    // Clear existing products to avoid duplicates during testing
    await Product.deleteMany();
    console.log("Existing products cleared.");

    // Insert seed data
    await Product.insertMany(products);
    console.log("Database seeded successfully! 🌱");
    // console.log("Inserted products:", products);

    // process.exit();
  } catch (error) {
    console.error("Error seeding database:", error);
    process.exit(1);
  }
};

